


GET http://localhost:3030/detallereportesalida/1

###

POST http://localhost:3030/detallereportesalida
Content-Type: application/json

{
    
  "PK_fk_Id_salida": "1",
  "PK_fk_Id_bodega": "1",
  "PK_fk_Id_producto": "1",
  "Cantidad_total_salidas": "50"
}
